Dotnet/expense tracher/expense tracher/Controllers/CategoryController.cs
using expense_tracher.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;

namespace expense_tracher.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ExpenseTrackerDbContext _context;
        public CategoryController(ExpenseTrackerDbContext context)
        {
            _context = context;
        }
        // GET: CategoryController
        public ActionResult Index()
        {
            var data = _context.TblCategories.Where(x => x.IsDeleted != true).ToList();
            return View(data);
        }
        
        // GET: CategoryController/Details/5
        public ActionResult Details(int id)
        {
            var data = _context.TblCategories.Where(x=> x.Id == id).FirstOrDefault();
            return View(data);
        }

        // GET: CategoryController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CategoryController/Create
        [HttpPost]
        public ActionResult Create(CategoryViewModel categoryViewModel)
        {
            try
            {
                if(!ModelState.IsValid)
                {
                    TempData["ErrorMessage"] = "Invalid input.";
                    return View(categoryViewModel);
                }
                var isExist = _context.TblCategories.Any(c => c.Name  == categoryViewModel.Name);
                if (isExist)
                {
                    TempData["ErrorMessage"] = "Category already exist.";
                    return View(categoryViewModel);
                }
                TblCategory category = new TblCategory() 
                {
                    Name = categoryViewModel.Name,
                    Description = categoryViewModel.Description,
                    CreatedAt = DateTime.UtcNow,
                    ModifiedAt = DateTime.UtcNow,
                    IsDeleted = false
                };
                _context.TblCategories.Add(category);
                _context.SaveChanges();
                TempData["SuccessMessage"] = "Category saved successfully!";
                return RedirectToAction("Create");
            }
            catch
            {
                TempData["ErrorMessage"] = "Something went wrong. Please try again.";
                return View(categoryViewModel);
            }
        }

        // GET: CategoryController/Edit/5
        public ActionResult Edit(int id)
        {
            var data = _context.TblCategories.Where(x => x.Id == id).FirstOrDefault();
            CategoryViewModel categoryViewModel = new CategoryViewModel() 
            {
                Id = data.Id,
                Name = data.Name,
                Description = data.Description,
            };
            return View(categoryViewModel);
        }

        [HttpPost]
        public ActionResult Edit(CategoryViewModel categoryViewModel)
        {
            try
            {
                var data = _context.TblCategories.Where(x => x.Id == categoryViewModel.Id).FirstOrDefault();
                if (data != null)
                {
                    data.Name = categoryViewModel.Name;
                    data.Description = categoryViewModel.Description;
                    data.ModifiedAt = DateTime.UtcNow;
                    _context.TblCategories.Update(data);
                    _context.SaveChanges();
                    TempData["SuccessMessage"] = "Category updated successfully!";
                }
                return RedirectToAction("Edit");
            }
            catch
            {
                TempData["ErrorMessage"] = "Something went wrong. Please try again.";
                return View(categoryViewModel);
            }
        }

        // GET: CategoryController/Delete/5
        public ActionResult Delete(int id)
        {
            var data = _context.TblCategories.Where(x => x.Id == id).FirstOrDefault();
            return View(data);
        }

        [HttpPost]
        public IActionResult DeleteTransaction(int id)
        {
            var data = _context.TblCategories.FirstOrDefault(x => x.Id == id);
            data.IsDeleted = true;
            _context.TblCategories.Update(data);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Dotnet/expense tracher/expense tracher/Controllers/IncomeController.cs
using expense_tracher.Enum;
using expense_tracher.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace expense_tracher.Controllers
{
    public class IncomeController : Controller
    {
        private readonly ExpenseTrackerDbContext _context;
        public IncomeController(ExpenseTrackerDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(DateTime? fromDate, DateTime? toDate)
        {
            var userIdString = User.FindFirst("Id")?.Value;
            int userId = int.Parse(userIdString);
            List<IncomeViewModel> incomeViewModels = new List<IncomeViewModel>();
            //var expense = _context.TblTransactions.Where(x => x.IsDeleted != true).ToList();
            var incomeResult = await (from income in _context.TblTransactions
                                       join category in _context.TblCategories on income.CategoryId equals category.Id
                                       join paymentMode in _context.TblPaymentModes on income.PaymentModeId equals paymentMode.Id
                                       where income.IsDeleted != true && income.PaymentTypeId == 1 && income.UserId == userId
                                      select new IncomeViewModel
                                       {
                                           Id = income.Id,
                                           Name = income.Name,
                                           Category = category.Name,
                                           Amount = income.Amount,
                                           PaymentMode = paymentMode.PaymentMode,
                                           CreatedAt = income.CreatedAt,
                                       }
                                       ).ToListAsync();
            if (fromDate.HasValue)
            {
                incomeResult = incomeResult.Where(x => x.CreatedAt <= toDate).ToList();
            }
            if (toDate.HasValue)
            {
                incomeResult = incomeResult.Where(x => x.CreatedAt <= toDate).ToList();
            }
            return View(incomeResult);

        }
        public IActionResult Create()
        {
            try
            {
                var category = _context.TblCategories.ToList();
                List<CategoryViewModel> categoryViewModel = new List<CategoryViewModel>();

                foreach (var item in category)
                {
                    categoryViewModel.Add(new CategoryViewModel
                    {
                        Id = item.Id,
                        Name = item.Name
                    });
                }
                IncomeViewModel incomeViewModel = new IncomeViewModel()
                {
                    categoryList = categoryViewModel
                };
                return View(incomeViewModel);
            }
            catch
            {

            }
            return View();
        }
        [HttpPost]
        public IActionResult Create(IncomeViewModel incomeViewModel)
        {
            try
            {
                var userIdString = User.FindFirst("Id")?.Value;
                int userId = int.Parse(userIdString);
                TblTransaction tblTransaction = new TblTransaction()
                {
                    Name = incomeViewModel.Name,
                    Note = incomeViewModel.Note,
                    Amount = incomeViewModel.Amount,
                    PaymentModeId = incomeViewModel.PaymentModeId,
                    PaymentTypeId = 1,
                    CreatedAt = DateTime.UtcNow,
                    ModifiedAt = DateTime.UtcNow,
                    IsDeleted = false,
                    CategoryId = incomeViewModel.CategoryId,
                    UserId = userId,
                };
                _context.TblTransactions.Add(tblTransaction);
                _context.SaveChanges();
                TempData["SuccessMessage"] = "Income saved successfully!";
                return RedirectToAction("Create");
            }
            catch
            {
                TempData["ErrorMessage"] = "Something went wrong. Please try again.";
                return View();
            }
        }
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                
                IncomeViewModel incomeViewModel = new IncomeViewModel();
                var categoryList = _context.TblCategories.ToList();
                List<CategoryViewModel> categoryViewModel = new List<CategoryViewModel>();

                foreach (var item in categoryList)
                {
                    categoryViewModel.Add(new CategoryViewModel
                    {
                        Id = item.Id,
                        Name = item.Name
                    });
                }
                var incomeResult = await(from income in _context.TblTransactions
                                         join category in _context.TblCategories on income.CategoryId equals category.Id
                                         join paymentMode in _context.TblPaymentModes on income.PaymentModeId equals paymentMode.Id
                                         where income.Id == id
                                         select new IncomeViewModel
                                         {
                                             Id = income.Id,
                                             Name = income.Name,
                                             Category = category.Name,
                                             CategoryId = income.CategoryId,
                                             Amount = income.Amount,
                                             PaymentMode = paymentMode.PaymentMode,
                                             PaymentModeId = income.PaymentModeId
                                         }
                                      ).FirstOrDefaultAsync();
                if (incomeResult != null)
                {
                    incomeViewModel = incomeResult;
                    incomeViewModel.categoryList = categoryViewModel;
                }
                return View(incomeViewModel);
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public IActionResult Edit(IncomeViewModel incomeViewModel)
        {
            try
            {
                var data = _context.TblTransactions.Where(x => x.Id == incomeViewModel.Id).FirstOrDefault();
                data.Note = incomeViewModel.Note;
                data.Name = incomeViewModel.Name;
                data.Amount = incomeViewModel.Amount;
                data.PaymentModeId = incomeViewModel.PaymentModeId;
                data.ModifiedAt = DateTime.UtcNow;
                data.CategoryId = incomeViewModel.CategoryId;
                _context.TblTransactions.Update(data);
                _context.SaveChanges();
                TempData["SuccessMessage"] = "Income updated successfully!";
                return RedirectToAction("Edit");
            }
            catch
            {
                TempData["ErrorMessage"] = "Something went wrong. Please try again.";
                return View();
            }
        }
        public IActionResult Delete(int id)
        {
            var data = _context.TblTransactions.Where(x => x.Id == id).FirstOrDefault();
            return View(data);
        }

        [HttpPost]
        public IActionResult DeleteTransaction(int id)
        {
            var data = _context.TblTransactions.Where(x => x.Id == id).FirstOrDefault();
            data.IsDeleted = true;
            _context.TblTransactions.Update(data);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                IncomeViewModel incomeViewModel = new IncomeViewModel();
                var incomeResult = await(from income in _context.TblTransactions
                                         join category in _context.TblCategories on income.CategoryId equals category.Id
                                         join paymentMode in _context.TblPaymentModes on income.PaymentModeId equals paymentMode.Id
                                         where income.Id==id
                                         select new IncomeViewModel
                                         {
                                             Id = income.Id,
                                             Name = income.Name,
                                             Category = category.Name,
                                             Amount = income.Amount,
                                             PaymentMode = paymentMode.PaymentMode,
                                             CreatedAt = income.CreatedAt,
                                             ModifiedAt = income.ModifiedAt
                                         }
                                      ).FirstOrDefaultAsync();
                if (incomeResult != null)
                {
                    incomeViewModel = incomeResult;
                }
                return View(incomeViewModel);
            }
            catch
            {
                return View();
            }
           
        }
    }
}

Dotnet/expense tracher/expense tracher/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - expense_tracher</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/expense_tracher.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div class="d-flex justify-content-between">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/logo.png" width="50px" alt="Alternate Text" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Income"asp-action="Index">Income</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Expense" asp-action="Index">Expense</a>
                        </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-dark" href="#" id="profileDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Profile
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="profileDropdown">
                                    <li>
                                        <a class="dropdown-item" asp-area="" asp-controller="AppUser" asp-action="ChangePassword">Change Password</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="" asp-controller="AppUser" asp-action="ProfileEdit">Edit Profile</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="" asp-controller="AppUser" asp-action="logout">logout</a>
                                    </li>
                                </ul>
                            </li>
                    </ul>
                </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>